version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: back/Dockerfile
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: myuser
      DB_PASSWORD: mypassword
      DB_NAME: mydb
    env_file:
      - ./back/.env
    depends_on:
      - postgres
    ports:
      - "3000:3000"

  frontend:
    build:
      context: .
      dockerfile: front/Dockerfile
    env_file:
      - ./front/.env
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  pgdata:
